blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/tomaszszymanski129/saleor/discussions
    about: If you have a support question or need help getting Saleor to work, please use GitHub Discussions.
