name: Create tag on release PR.
on:
  pull_request:
    types:
     - labeled

jobs:
  run-release-trigger:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'release')
    env:
      GH_REF: ${{ github.event.pull_request.head.ref }}
    steps:
      - run: echo "PR_TAG_REF=$GH_REF" | sed "s/release-//" >> $GITHUB_ENV
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.PR_TAG_REF }}",
              sha: context.sha
            })
  