name: Create tag and release on release PR merge
on:
  pull_request:
    types:
     - closed

jobs:
  prepare-tag:
    runs-on: ubuntu-latest
    env:
      GH_REF: ${{ github.event.pull_request.head.ref }}
    steps:
      - name: Prepare release tag version
        id: prepare-tag
        run: echo "PR_TAG_REF=$GH_REF" | sed "s/release-//" >> $GITHUB_OUTPUT

  run-release-trigger:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    env:
      GH_REF: ${{ github.event.pull_request.head.ref }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${steps.prepare-tag.outputs.PR_TAG_REF}`,
              sha: context.sha
            })
      - run: |
          gh release create "${{ steps.prepare-tag.outputs.PR_TAG_REF }}" --repo="$GITHUB_REPOSITORY" --generate-notes --draft --verify-tag
  
  testflow:
    runs-on: ubuntu-latest
    name: hope this works
    steps:
      - uses: ./.github/workflows/testflow.yml
        with:
          version: "${{ steps.prepare-tag.outputs.PR_TAG_REF }}"
