name: Test of action after merge release
on:
  pull_request:
    types: [labeled, closed]

jobs:
  run-release-trigger:
    if: github.event.pull_request.merged == true && contains( github.event.pull_request.labels.*.name, 'release')
    steps:
      - run: echo "Release PR is merged!"
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/<tagname>',
              sha: context.sha
            })