name: Publish

on:
  workflow_call:
    inputs:
      version:
        description: Optional custom image version tag
        required: false
        type: string

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: hehe
        env:
          VERSION_TAG: ${{ inputs.prefix }}
        run: echo "$VERSION_TAG"